# This is a basic workflow to help you get started with Actions

name: Sample Scanner

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  sample-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Sample Scanner
        uses: pnp/action-sample-scanner@main
        with:
          dirs: '["samples"]'
          token: ${{ secrets.GITHUB_TOKEN }}
